# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='tagId',
            new_name='tag_id',
        ),
    ]
