# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0002_auto_20170905_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
